Repository elastic/elasticsearch-net-abstractions, pull requests merged in 2023-07, with the labels that each got.

#58 NetFx: Add workaround for unsupported `HttpClientHandler.SslProtocols`
  src/Elastic.Stack.ArtifactsApi/Resolvers/ApiResolver.cs
Labels: bug, v0.4.1

#59 AutoWire detected proxies during setup
  examples/Elastic.Ephemeral.Example/Elastic.Ephemeral.Example.csproj
  examples/Elastic.Ephemeral.Example/Program.cs
  examples/ScratchPad/Program.cs
  examples/ScratchPad/ValidateCombinations.cs
  src/Elastic.Elasticsearch.Ephemeral/EphemeralCluster.cs
  src/Elastic.Elasticsearch.Ephemeral/EphemeralClusterConfiguration.cs
  src/Elastic.Elasticsearch.Ephemeral/Tasks/IClusterComposeTask.cs
  src/Elastic.Elasticsearch.Ephemeral/Tasks/InstallationTasks/PrintConfiguration.cs
  src/Elastic.Elasticsearch.Managed/ClusterBase.cs
  src/Elastic.Elasticsearch.Managed/Configuration/ClusterConfiguration.cs
  src/Elastic.Elasticsearch.Managed/DetectedProxySoftware.cs
Labels: enhancement, v0.4.2

#60 Ensure IEphemeralCluster extends ICluster
  src/Elastic.Elasticsearch.Ephemeral/IEphemeralCluster.cs
  src/Elastic.Elasticsearch.Managed/ClusterBase.cs
  src/Elastic.Elasticsearch.Xunit/XunitClusterExtensions.cs
Labels: enhancement, v0.4.3
